Plexus v0.9.48 - Progress bars for file movement
- Added progress as a package dependency
- Added progress bars to cp and mv commands
- Changed the RClone progress output to be more simplistic
- Minor syntax enhancements

diff --git a/plexus b/plexus
--- a/plexus
+++ b/plexus
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-HEADER_TEXT="\\e[93m=== Plexus v0.9.47 - https://github.com/Wolveix/Plexus ===\\e[0m\\n"
+HEADER_TEXT="\\e[93m=== Plexus v0.9.48 - https://github.com/Wolveix/Plexus ===\\e[0m\\n"
 set -e
 if [ -f "$HOME"/.config/plexus/plexus.conf ]; then
   source "$HOME"/.config/plexus/plexus.conf
@@ -388,7 +388,7 @@ function func_encode {
     ffmpeg_verbose="-loglevel quiet"
   fi
 
-  if [ ! -z "$rclone_bwlimit" ]; then
+  if [ -n "$rclone_bwlimit" ]; then
     if ! [[ "$rclone_bwlimit" =~ ^[0-9]+$ ]]; then
       printf "You have not entered a valid number for --bwlimit (do not include KB).\\n"
       exit 0
@@ -408,10 +408,10 @@ function func_encode {
       FILE=${line##*/}
       NAME=${FILE%.*}
       if [ "$remote_transfer" = true ]; then
-        if [ ! -z "$rclone_remote" ]; then
+        if [ -n "$rclone_remote" ]; then
           if [ "$dependency_rclone" = true ]; then
             printf "Downloading: $FILE\\n"
-            if ! $rclone_binary copy "$rclone_remote$line" "$convert_dir" $rclone_bwlimit --stats-log-level NOTICE --stats 30s
+            if ! $rclone_binary copy "$rclone_remote$line" "$convert_dir" $rclone_bwlimit --stats-one-line -P
             then
               printf "\\n\e[31mError: File could not be downloaded.\\n\\n\e[0mMoving onto the next line.\\n\\n"
               /bin/sed -i 1d "$list_file"
@@ -429,7 +429,7 @@ function func_encode {
       else
         if [ -f "$line" ]; then
           printf "Copying: $FILE\\n"
-          /bin/cp "$line" "$convert_dir"
+          /bin/cp "$line" "$convert_dir" & progress -mp $!
           printf "\\nFile copied."
           file_exists=1
         else
@@ -456,7 +456,7 @@ function func_encode {
             do
               counter=$((counter+1))
               excluded_stream="$(echo "$stream_id" |& grep -oP '0:[0-9]{1,3}' |& sed -n "${counter}"p)"
-              if [ ! -z "$excluded_stream" ]; then
+              if [ -n "$excluded_stream" ]; then
                 if [ "$exclude_stream" = "*$excluded_stream*" ]; then
                   counter="$stream_count"
                 else
@@ -474,7 +474,7 @@ function func_encode {
         fi
 
         if [ "$audio_codec" = "aac" ]; then
-          if [ ! -z "`$ffmpeg_binary -encoders |& grep -i libfdk`" ]; then
+          if [ -n "`$ffmpeg_binary -encoders |& grep -i libfdk`" ]; then
             audio_codec="libfdk_aac"
             ffmpeg_error="\\nAn unknown error occurred with FFmpeg.\\n"
           else
@@ -506,7 +506,7 @@ function func_encode {
         if ! $ffmpeg_binary -y -i "$convert_dir/$FILE" $codecs $options -nostdin $ffmpeg_verbose -stats "$converted_dir/$NAME.$media_container"; then
           if [ "$codec_copy" = true ]; then
             printf "\\n\\nAn unknown error occurred with FFmpeg.\\nTrying with full conversion instead.\\n\\n"
-            if [ ! -z "$audio_codec" ]; then
+            if [ -n "$audio_codec" ]; then
               encode_audio_codec="$audio_codec"
             fi
 
@@ -523,10 +523,10 @@ function func_encode {
 
         printf "\\nFile successfully converted."
         if [ -f "$convert_dir/$FILE" ]; then
-          if [ ! -z "$rclone_remote" ]; then
+          if [ -n "$rclone_remote" ]; then
             if [ "$force_overwrite" = true ]; then
               printf "\\nDeleting original file from RClone remote.\\n"
-              $rclone_binary delete "$rclone_remote$line" $rclone_bwlimit --stats-log-level NOTICE --stats 30s
+              $rclone_binary delete "$rclone_remote$line" $rclone_bwlimit --stats-one-line -P
               printf "\\nOriginal file deleted."
             else
               mv "$converted_dir/$NAME.$media_container" "$converted_dir/$NAME [Plexus Encode].$media_container"
@@ -534,7 +534,7 @@ function func_encode {
               printf "\\nForce overwrite is disabled, new filename = $NAME.$media_container"
             fi
             printf "\\nUploading converted file to RClone remote.\\n"
-            $rclone_binary move "$converted_dir/$NAME.$media_container" "$rclone_remote$DIRP" $rclone_bwlimit --stats-log-level NOTICE --stats 30s
+            $rclone_binary move "$converted_dir/$NAME.$media_container" "$rclone_remote$DIRP" $rclone_bwlimit --stats-one-line -P
             printf "\\nFile successfully uploaded."
           else
             if [ "$force_overwrite" = true ]; then
@@ -547,7 +547,7 @@ function func_encode {
               printf "\\nForce overwrite is disabled, new filename = $NAME.$media_container"
             fi
             printf "\\nMoving converted file to the correct location.\\n"
-            /bin/mv "$converted_dir/$NAME.$media_container" "$line"
+            /bin/mv "$converted_dir/$NAME.$media_container" "$line" & progress -mp $!
             printf "\\nFile successfully moved."
           fi
           printf "\\nDeleting cached file and delisting it.\\n"
@@ -582,7 +582,7 @@ function func_install {
           case "$option" in
             "All")
               printf "\\n\\e[36mInstalling all dependencies.\\e[0m\\n\\n"
-              $packages install curl ffmpeg fuse unzip
+              $packages install curl ffmpeg fuse progress unzip
               curl https://rclone.org/install.sh 2>/dev/null | sudo bash
               ;;
             "FFmpeg")
@@ -750,113 +750,113 @@ case "$command" in
   config)
     func_config
     ;;
-  encode)
-    while getopts ":a:fl:p:r:v:-:" opt; do
-      case $opt in
-        a)
-          if [ -z "${OPTARG,,}" ]; then
-            if [ -z "$video_codec" ]; then
-              printf "\\n\\e[31mYou've specified no audio or video codec, please specify at least one\\n"
-              exit 0
+    encode)
+      while getopts ":a:fl:p:r:v:-:" opt; do
+        case $opt in
+          a)
+            if [ -z ${OPTARG,,} ]; then
+              if [ -z "$video_codec" ]; then
+                printf "\\n\\e[31mYou've specified no audio or video codec, please specify at least one\\n"
+                exit 0
+              else
+                printf "\\n\\e[93mYou've specified no audio codec, enabling video-only mode"
+                encode_audio_codec="$audio_codec"
+                audio_codec=""
+              fi
             else
-              printf "\\n\\e[93mYou've specified no audio codec, enabling video-only mode"
-              encode_audio_codec="$audio_codec"
-              audio_codec=""
+              check_variable audio ${OPTARG,,}
+              if [ $audio_codec = "null" ]; then
+                printf "You have not entered a supported audio codec.\\n"
+                exit 0
+              fi
             fi
-          else
-            check_variable audio "${OPTARG,,}"
-            if [ $audio_codec = "null" ]; then
-              printf "You have not entered a supported audio codec.\\n"
+            ;;
+          f)
+            force_overwrite="true"
+            ;;
+          l)
+            if [ -f "$OPTARG" ]; then
+              list_file="$OPTARG"
+            else
+              printf "You have not entered a valid list file.\\n"
+              exit 1
+            fi
+            ;;
+          p)
+            check_variable ffmpeg_preset ${OPTARG,,}
+            if [ $ffmpeg_preset = "null" ]; then
+              printf "You have not entered a valid ffmpeg preset.\\n"
               exit 0
             fi
-          fi
-          ;;
-        f)
-          force_overwrite="true"
-          ;;
-        l)
-          if [ -f "$OPTARG" ]; then
-            list_file="$OPTARG"
-          else
-            printf "You have not entered a valid list file.\\n"
+            ;;
+          r)
+            $rclone_binary listremotes > $HOME/.plexus/rclone/remotes.txt
+            if [ ! -z "$(grep "$OPTARG" "$HOME/.plexus/rclone/remotes.txt")" ]; then
+              if [ "${OPTARG: -1}" == ":" ]; then
+                  rclone_remote="$OPTARG"
+              else
+                  rclone_remote="$OPTARG:"
+              fi
+              remote_transfer=true
+            else
+              printf "You have not entered a valid remote.\\n"
+              exit 0
+            fi
+            ;;
+          v)
+            if [ -z ${OPTARG,,} ]; then
+              if [ -z "$audio_codec" ]; then
+                printf "\\n\\e[31mYou've specified no audio or video codec, please specify at least one\\n"
+                exit 0
+              else
+                printf "\\n\\e[93mYou've specified no video codec, enabling audio-only mode"
+                video_codec=""
+              fi
+            else
+              check_variable video ${OPTARG,,}
+              if [ $video_codec = "null" ]; then
+                printf "You have not entered a supported video codec.\\n"
+                exit 0
+              fi
+            fi
+            ;;
+          -)
+            val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
+            case ${OPTARG} in
+              "bwlimit"*)
+                rclone_bwlimit="$val"
+                ;;
+              "verbose"*)
+                verbose="true"
+                ;;
+            esac
+            ;;
+          \?)
+            echo "Invalid option: -$OPTARG." >&2
             exit 1
-          fi
-          ;;
-        p)
-          check_variable ffmpeg_preset "${OPTARG,,}"
-          if [ $ffmpeg_preset = "null" ]; then
-            printf "You have not entered a valid ffmpeg preset.\\n"
-            exit 0
-          fi
-          ;;
-        r)
-          $rclone_binary listremotes > "$HOME"/.plexus/rclone/remotes.txt
-          if [ -n "$(grep "$OPTARG" "$HOME/.plexus/rclone/remotes.txt")" ]; then
-            if [ "${OPTARG: -1}" == ":" ]; then
-                rclone_remote="$OPTARG"
-            else
-                rclone_remote="$OPTARG:"
-            fi
-            remote_transfer=true
-          else
-            printf "You have not entered a valid remote.\\n"
-            exit 0
-          fi
-          ;;
-        v)
-          if [ -z "${OPTARG,,}" ]; then
-            if [ -z "$audio_codec" ]; then
-              printf "\\n\\e[31mYou've specified no audio or video codec, please specify at least one\\n"
-              exit 0
-            else
-              printf "\\n\\e[93mYou've specified no video codec, enabling audio-only mode"
-              video_codec=""
-            fi
-          else
-            check_variable video "${OPTARG,,}"
-            if [ $video_codec = "null" ]; then
-              printf "You have not entered a supported video codec.\\n"
-              exit 0
-            fi
-          fi
-          ;;
-        -)
-          val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
-          case ${OPTARG} in
-            "bwlimit"*)
-              rclone_bwlimit="$val"
-              ;;
-            "verbose"*)
-              verbose="true"
-              ;;
-          esac
-          ;;
-        \?)
-          echo "Invalid option: -$OPTARG." >&2
-          exit 1
-          ;;
-        :)
-          echo "Option -$OPTARG requires an argument." >&2
-          exit 1
-          ;;
-      esac
-    done
-    if [ $OPTIND -eq 1 ]; then
-      printf "\\n\\e[39mUsage:\\n  plexus encode -l /path/to/list.txt [flags]\\n  plexus encode -l /path/to/list.txt -r RCloneRemote: [flags]\\n\\nFlags:\\n  -a              Audio codec. Default = $audio_codec\\n  -f              Force overwrite. Default = $force_overwrite\\n  -l              List location. Default = $list_file\\n  -p              FFMpeg preset. Default = $ffmpeg_preset\\n  -r              RClone remote. Use this for RClone integration\\n  -v              Video codec. Default = $video_codec\\n  --bwlimit       Limit RClone's active connection speed\\n  --verbose       Show detailed log\\n"
-      exit 0
-    fi
-    if [ -n "$list_file" ]; then
-      if [ $dependency_ffmpeg = true ]; then
-        func_encode
-      else
-        printf "\\e[31mPlease install ffmpeg to use this command\\e[0m\\n"
+            ;;
+          :)
+            echo "Option -$OPTARG requires an argument." >&2
+            exit 1
+            ;;
+        esac
+      done
+      if [ $OPTIND -eq 1 ]; then
+        printf "\\n\\e[39mUsage:\\n  plexus encode -l /path/to/list.txt [flags]\\n  plexus encode -l /path/to/list.txt -r RCloneRemote: [flags]\\n\\nFlags:\\n  -a              Audio codec. Default = $audio_codec\\n  -f              Force overwrite. Default = $force_overwrite\\n  -l              List location. Default = $list_file\\n  -p              FFMpeg preset. Default = $ffmpeg_preset\\n  -r              RClone remote. Use this for RClone integration\\n  -v              Video codec. Default = $video_codec\\n  --bwlimit       Limit RClone's active connection speed\\n  --verbose       Show detailed log\\n"
         exit 0
       fi
-    else
-      printf "You must specify a list file.\\n"
-    fi
-    shift $((OPTIND -1))
-    ;;
+      if [ ! -z "$list_file" ]; then
+        if [ $dependency_ffmpeg = true ]; then
+          func_encode
+        else
+          printf "\\e[31mPlease install ffmpeg to use this command\\e[0m\\n"
+          exit 0
+        fi
+      else
+        printf "You must specify a list file.\\n"
+      fi
+      shift $((OPTIND -1))
+      ;;
   help)
     case "${subcommand,,}" in
       "about")
